# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa150401320a3f8fe8f4f907bac4eb79af70f69fa9527909b42225c994e57027d14703ca65d7c3c514649457039cb7696291835d679521f7ee0301ca0926fa4

test:
  secret_key_base: 7c1a4bae9854665f84eff750bb6771b117123a179910ce4f46132892b6870ce35110f2a0234d442089298490c8f75de6275bf2057be70dda0e1ad8c42ad08dc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
